### PR TITLE
Translated improved admin page

### PR DESCRIPTION
**Pull request by JawaherAlsha**

### CODE REVIEW

**Comment by malmarz** [comment]
@JawaherAlsha remove the english text from the arabic file and you have moved 4 other files. Return them to where they were

**Comment by JawaherAlsha** [comment]
> @JawaherAlsha remove the english text from the arabic file and you have moved 4 other files. Return them to where they were

Dr. from here right? the "Files Changed" tool?

‏‏لقطة الشاشة (18)

**Comment by malmarz** [comment]
@JawaherAlsha The main file you translated is fine, but you have deleted some important files that I asked you all not to do anything with so you must do the following:
- Copy your translated file to a new file outside the current project and on your computer
- delete the current branch you are working on 
- switch to master/main branch and create a new branch from there
- copy the work you did to the same file on the new branch and do not change or move any other files
- create a new pull request

**Comment by JawaherAlsha** [comment]
@malmarz 

I am sorry about that Dr.
and thanks for explaining but it says i can't delete the branch because it has an open pull request 
and i can't delete the branch from replit.

‏‏لقطة الشاشة (22)

**Comment by malmarz** [comment]
@JawaherAlsha then ignore the branch.. I will delete it later... be sure to switch to main and create a new branch to do you new work and create a new pull request from it

**Comment by JawaherAlsha** [comment]
> @JawaherAlsha then ignore the branch.. I will delete it later... be sure to switch to main and create a new branch to do you new work and create a new pull request from it

Done.

**Pull request closed without merging**
